script: "bundle exec rake -f spec/dummy/Rakefile db:drop jackpot:install:migrations db:create db:migrate db:test:clone; bundle exec rspec spec"

rvm:
  - 2.0.0
  - 1.9.3
  - rbx
  - jruby

notifications:
  irc: "irc.freenode.org#jackpot"

