development:
  host: localhost
  adapter: mysql2
  database: jackpot_development
  username: root
  pool: 5
  encoding: utf8
  reconnect: false

test: &test
  host: localhost
  adapter: mysql2
  database: jackpot_test<%= ENV['TEST_ENV_NUMBER'] %>
  username: root
  reconnect: false
  pool: 5
  encoding: utf8
